# Generated by Django 3.2.5 on 2021-07-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncaa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncaa.conference')),
            ],
            options={
                'verbose_name_plural': 'teams',
            },
        ),
    ]
