# Generated by Django 3.2.5 on 2021-07-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncaa', '0006_player_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
