# Generated by Django 3.2.5 on 2021-07-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncaa', '0008_player_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
    ]
